name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Generate CalVer version
        id: calver
        run: |
          export VERSION=$(date "+%Y.%m.%d")
          gh release list -O desc -L 1 --json name -q [].name | grep -v $VERSION
          if [[ $? -eq 0 ]]; then
            export VERSION=${VERSION}_1
          else
            export VERSION=$(echo $VERSION | sed -E 's/(.*_)([0-9]+)/echo "\1$((\2+1))"/e')
          fi
          echo ::set-output name=version::${VERSION}
          echo "Version set to ${VERSION}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: release-drafter/release-drafter@v6
        with:
          version: ${{ steps.calver.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
